# Generated by Django 5.0.6 on 2024-08-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_app', '0003_fielddata_blocknumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
